import { useEffect, useState } from 'react'
import { clearTtsCache, loadTtsCacheSettings, saveTtsCacheSettings, ttsCacheUsage, type TtsCacheSettings as Settings } from './tts-cache'
export default function TtsCacheSettings({ bookId }: { bookId?: string }) {
  const [settings, setSettings] = useState(loadTtsCacheSettings), [bytes, setBytes] = useState(0), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { let live = true; const refresh = () => { if (live) setSettings(loadTtsCacheSettings()); void ttsCacheUsage().then(value => { if (live) setBytes(value) }).catch(() => { if (live) setError('Audio cache size is temporarily unavailable.') }) }; refresh(); window.addEventListener('arc-tts-cache-changed', refresh); window.addEventListener('storage', refresh); return () => { live = false; window.removeEventListener('arc-tts-cache-changed', refresh); window.removeEventListener('storage', refresh) } }, [])
  function save(next: Settings) { try { saveTtsCacheSettings(next); setSettings(next); setError('') } catch { setError('Could not save audio cache settings.') } }
  async function clear(all: boolean) { setBusy(true); setError(''); try { await clearTtsCache(all ? undefined : bookId); setBytes(await ttsCacheUsage()) } catch { setError('Could not clear cached audio. Try again.') } finally { setBusy(false) } }
  return <section className="settings-card tts-cache-settings"><div className="card-heading"><div><h2>Audio cache</h2></div><p>{(bytes / 1024 ** 2).toFixed(1)} MiB used on this device</p></div><p className="speech-help">Identical spoken chunks can replay offline without another paid request. Cache settings apply across books on this device. Audio is disposable and excluded from book backups.</p><div className="speech-settings-grid"><label className="speech-toggle"><span><input type="checkbox" checked={settings.enabled} onChange={e => save({ ...settings, enabled: e.target.checked })} /> Cache speech audio</span><small>Turning off keeps stored audio and stops cache reads and writes.</small></label><label>Maximum storage<select aria-label="Audio cache maximum" value={settings.maxMiB} onChange={e => save({ ...settings, maxMiB: Number(e.target.value) as Settings['maxMiB'] })}>{[64, 256, 512].map(size => <option value={size} key={size}>{size} MiB</option>)}</select></label></div><div className="author-actions">{bookId && <button type="button" disabled={busy} onClick={() => { void clear(false) }}>Clear current book audio</button>}<button type="button" disabled={busy} onClick={() => { void clear(true) }}>Clear all audio</button></div>{error && <p role="alert">{error}</p>}</section>
}
