import { useEffect, useRef, useState } from 'react'
import type { CodexEntryEntity } from '../../data/persistence'
import { getEntity } from '../../data/persistence'
import { checkpointPlaced, resolveCodexState, timelineScenes, type CodexCheckpoint, type TimelineWorld, type TimelineMode } from './codex-timeline'
import { generateTimelineSummary, readTimelineWorld, saveCodexCheckpoints } from './codex-timeline-service'
import Button from '../../shared/ui/Button'
import Disclosure from '../../shared/ui/Disclosure'
import ExpandableTextInput from '../../shared/ui/ExpandableTextInput'
import Input from '../../shared/ui/Input'
import Select from '../../shared/ui/Select'
import './codex-ui-kit.css'

export default function CodexTimeline({ bookId, entry, currentSceneId, disabled, onBeforeChange, onRefresh, onViewChange }: { bookId: string; entry: CodexEntryEntity; currentSceneId?: string; disabled?: boolean; onBeforeChange: () => Promise<void>; onRefresh: () => Promise<void>; onViewChange?: (nonBaseline: boolean) => void }) {
  const [world, setWorld] = useState<TimelineWorld>(), [value, setValue] = useState(entry), [view, setView] = useState('baseline'), [draft, setDraft] = useState<CodexCheckpoint>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [summaryMode, setSummaryMode] = useState<TimelineMode>('cutoff')
  const controller = useRef<AbortController | null>(null)
  const refresh = async () => { const latest = await getEntity<CodexEntryEntity>(entry.id); if (latest) setValue(latest); setWorld(await readTimelineWorld(bookId)) }
  useEffect(() => { let live = true; const load = () => { void Promise.all([getEntity<CodexEntryEntity>(entry.id), readTimelineWorld(bookId)]).then(([entry, world]) => { if (live) { if (entry) setValue(entry); setWorld(world) } }).catch(e => { if (live) setError(e.message) }) }; load(); window.addEventListener('focus', load); window.addEventListener('arc-series-codex-changed', load); return () => { live = false; controller.current?.abort(); window.removeEventListener('focus', load); window.removeEventListener('arc-series-codex-changed', load) } }, [bookId, entry.id])
  const readOnly = disabled || entry.codexScope === 'inherited' || Boolean(entry.archivedAt)
  const points = value.checkpoints ?? []
  let resolved: ReturnType<typeof resolveCodexState> | undefined, resolutionError = ''
  try { if (world && currentSceneId) resolved = resolveCodexState(value, { bookId, sceneId: currentSceneId }, world) } catch (reason) { resolutionError = (reason as Error).message }
  const run = async (action: () => Promise<void>) => { if (busy) return; setBusy(true); setError(''); try { await onBeforeChange(); await action(); await refresh(); await onRefresh() } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  const choose = (next: string) => { void run(async () => { setView(next); setDraft(undefined); onViewChange?.(next !== 'baseline') }) }
  const selected = points.find(point => point.id === view)
  return <Disclosure className="codex-timeline" title={`Story checkpoints · ${points.length}`} description={resolved ? (resolved.checkpointId === 'baseline' ? 'Baseline active' : 'Checkpoint active') : undefined}>
    <p>Baseline contains facts valid at the start. Checkpoints take effect at the start of their scene. Inspecting or editing one does not move the AI’s story cutoff.</p>
    <Select label="View" aria-label="Codex timeline view" disabled={busy || Boolean(draft)} value={view} onChange={e => choose(e.target.value)}><option value="baseline">Baseline</option><option value="as-of">As of current scene</option>{points.map(point => <option key={point.id} value={point.id}>{point.label}{world && !checkpointPlaced(point, world) ? ' · Unplaced' : ''}{point.id === resolved?.checkpointId ? ' · Active' : ''}</option>)}</Select>
    <ul>{points.map(point => <li key={point.id} className={world && !checkpointPlaced(point, world) ? 'unplaced' : ''}><strong>{point.label}</strong> · {world?.books.find(book => book.id === point.anchorBookId)?.title || 'Unavailable book'} / {world?.outline.find(scene => scene.id === point.sceneId)?.title || 'Unplaced scene'}{point.id === resolved?.checkpointId ? ' · Active' : ''}</li>)}</ul>
    {view === 'baseline' && <p>Use the baseline editor below.</p>}
    {view === 'as-of' && <><p>{resolutionError || (!resolved ? 'Choose a current scene to resolve this entry.' : resolved.checkpointId === 'baseline' ? 'Baseline at the current scene' : 'Eligible checkpoint body')}</p>{resolved && <pre>{resolved.content}</pre>}</>}
    {selected && !draft && <><pre>{selected.content || 'Empty state'}</pre><Button size="small" disabled={readOnly || busy} onClick={() => setDraft({ ...selected })}>Edit checkpoint</Button><Button size="small" variant="danger" disabled={readOnly || busy} onClick={() => { void run(async () => { await saveCodexCheckpoints(bookId, entry.id, points, points.filter(point => point.id !== selected.id)); setView('baseline'); onViewChange?.(false) }) }}>Delete checkpoint</Button></>}
    {!draft && <Button size="small" disabled={readOnly || busy} onClick={() => { void run(async () => { const latest = await getEntity<CodexEntryEntity>(entry.id); setDraft({ id: `checkpoint-${crypto.randomUUID()}`, label: '', anchorBookId: bookId, sceneId: currentSceneId ?? '', content: resolved?.content ?? latest?.content ?? '', revision: Date.now() }); onViewChange?.(true) }) }}>New checkpoint</Button>}
    {draft && <fieldset disabled={busy || readOnly}><Input label="Checkpoint label" aria-label="Checkpoint label" value={draft.label} onChange={e => { const label = e.target.value; setDraft(current => current ? { ...current, label } : current) }} /><Select label="Book" aria-label="Checkpoint book" value={draft.anchorBookId} onChange={e => { const anchorBookId = e.target.value; setDraft(current => current ? { ...current, anchorBookId, sceneId: '' } : current) }}>{world?.books.filter(book => book.id === bookId || value.seriesSourceId || value.codexScope === 'series').map(book => <option key={book.id} value={book.id}>{book.title} · {book.seriesOrder || 'order unset'}</option>)}</Select><Select label="Effective from scene" aria-label="Checkpoint scene" value={draft.sceneId} onChange={e => { const sceneId = e.target.value; setDraft(current => current ? { ...current, sceneId } : current) }}><option value="">Choose scene</option>{world && timelineScenes(world, draft.anchorBookId).map(scene => <option key={scene.id} value={scene.id}>{scene.title}</option>)}{draft.sceneId && world && !checkpointPlaced(draft, world) && <option value={draft.sceneId}>Unplaced — choose a new anchor</option>}</Select><label><span>Full state body</span><ExpandableTextInput aria-label="Checkpoint body" dialogTitle="Edit checkpoint body" value={draft.content} onChange={content => setDraft(current => current ? { ...current, content } : current)} /></label><p>Unsaved checkpoint changes. This is a full snapshot, independent of the baseline.</p><Button size="small" variant="ghost" onClick={() => { setDraft(undefined); onViewChange?.(view !== 'baseline') }}>Cancel checkpoint edit</Button><Button size="small" variant="primary" disabled={!draft.label.trim() || !draft.sceneId} onClick={() => { void run(async () => { await saveCodexCheckpoints(bookId, entry.id, points, [...points.filter(point => point.id !== draft.id), draft]); setView(draft.id); setDraft(undefined); onViewChange?.(true) }) }}>Save checkpoint</Button></fieldset>}
    {!draft && view !== 'as-of' && <div><Select label="Summary mode" value={summaryMode} onChange={e => setSummaryMode(e.target.value as TimelineMode)}><option value="cutoff">Story cutoff</option><option value="strict">Character cutoff (body only)</option></Select><Button size="small" disabled={busy || disabled} onClick={() => { void run(async () => { controller.current = new AbortController(); await generateTimelineSummary(bookId, entry.id, selected?.id ?? 'baseline', summaryMode, controller.current.signal) }) }}>Summarize this state</Button>{busy && controller.current && <Button size="small" variant="ghost" onClick={() => controller.current?.abort()}>Stop summary</Button>}<small>Uses the Support model. Cached for this exact body, story order, and cutoff mode.</small></div>}
    {(error || resolutionError) && <p role="alert">{error || resolutionError}</p>}
  </Disclosure>
}
