import CodexTimeline from './CodexTimeline'
import CodexTemplates from './CodexTemplates'
import { LoreTypeSelect } from './LoreTypesControls'
import { useEffect, useRef, useState } from 'react'
import { Redo2, Undo2 } from 'lucide-react'
import type { CodexEntryEntity } from '../../data/persistence'
import { createCodexEntry, getEntity, listOutgoingCodexDependencies } from '../../data/persistence'
import { codexScopeLabel } from './series-codex'
import { archiveSeriesSource, deleteSeriesSource, editCodexForBook, promoteCodexToSeries, readSeriesSource, resetCodexToSeries, saveSeriesSource, seriesCodexState, seriesSourceDraft, setSeriesEntryHidden, type SeriesSourceDraft } from './series-codex-service'
import IllustrationModal from '../images/IllustrationModal'
import CodexIllustration from './CodexIllustration'
import MarkdownEditor, { type MarkdownEditorHandle } from '../editor/MarkdownEditor'
import Button from '../../shared/ui/Button'
import Checkbox from '../../shared/ui/Checkbox'
import Input from '../../shared/ui/Input'
import './codex-ui-kit.css'

type SourceState = Awaited<ReturnType<typeof readSeriesSource>>
export function SeriesSourceEditor({ bookId, sourceId, onClose }: { bookId: string; sourceId: string; onClose: () => void }) {
  const [state, setState] = useState<SourceState>(), [draft, setDraft] = useState<SeriesSourceDraft>(), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const editor = useRef<MarkdownEditorHandle | null>(null)
  useEffect(() => { let active = true; void readSeriesSource(bookId, sourceId).then(value => { if (active) { setState(value); setDraft(seriesSourceDraft(value.source, value.edges)) } }).catch(reason => { if (active) setError(reason.message) }); return () => { active = false } }, [bookId, sourceId])
  const save = async () => { if (!state || !draft || busy) return; setBusy(true); setError(''); try { await saveSeriesSource(bookId, sourceId, seriesSourceDraft(state.source, state.edges), draft); onClose() } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  return <IllustrationModal title="Edit series source" onClose={() => { if (!busy) onClose() }} fullScreen footer={<><Button variant="ghost" disabled={busy} onClick={onClose}>Close</Button><Button variant="primary" className="image-primary" disabled={busy || !draft || Boolean(state?.source.archivedAt)} onClick={() => { void save() }}>Save series changes</Button></>}>
    {state && draft ? <div className="series-source-editor"><p><strong>Shared edit · {state.series?.title}</strong><br />{state.books.length} books: {state.books.map(book => book.title).join(', ')}. Inheriting books receive these changes; local overrides keep their copies.</p>
      <CodexIllustration entry={state.source} readOnly={Boolean(state.source.archivedAt)}><strong>{draft.title}</strong></CodexIllustration><small>Image edits save immediately to the series source.</small>
      <fieldset disabled={busy || Boolean(state.source.archivedAt)}><Input label="Title" aria-label="Series entry title" value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /><label>Category<LoreTypeSelect ownerId={state.source.bookId} value={draft.typeId ?? draft.category} disabled={busy || Boolean(state.source.archivedAt)} onChange={typeId => setDraft({ ...draft, typeId })} /></label><label>Automatic triggers<textarea className="arc-input codex-textarea" value={(draft.autoIncludeTriggers ?? []).join('\n')} onChange={event => setDraft({ ...draft, autoIncludeTriggers: event.target.value.split('\n').map(text => text.trim()).filter(Boolean) })} /></label>
      <details><summary>Series relationships</summary>{state.sources.filter(item => item.id !== sourceId).map(target => { const edge = draft.edges.find(item => item.targetId === target.id); return <div className="series-relationship" key={target.id}><Checkbox label={target.title} checked={Boolean(edge)} onChange={event => setDraft({ ...draft, edges: event.target.checked ? [...draft.edges, { targetId: target.id, relationLabel: '', includeWithSource: true }] : draft.edges.filter(item => item.targetId !== target.id) })} />{edge && <><Input aria-label={`Relationship to ${target.title}`} value={edge.relationLabel} onChange={event => setDraft({ ...draft, edges: draft.edges.map(item => item.targetId === target.id ? { ...item, relationLabel: event.target.value } : item) })} /><Checkbox label="Include with source" checked={edge.includeWithSource} onChange={event => setDraft({ ...draft, edges: draft.edges.map(item => item.targetId === target.id ? { ...item, includeWithSource: event.target.checked } : item) })} /></>}</div> })}</details></fieldset>
      <CodexTimeline bookId={bookId} entry={state.source} disabled={busy} onBeforeChange={async () => { if (JSON.stringify(draft) !== JSON.stringify(seriesSourceDraft(state.source, state.edges))) throw new Error('Save or discard the series body/metadata draft before editing checkpoints.') }} onRefresh={async () => { const next = await readSeriesSource(bookId, sourceId); setState(next); setDraft(seriesSourceDraft(next.source, next.edges)) }} />
      <CodexTemplates bookId={bookId} targetId={sourceId} typeId={draft.typeId ?? draft.category} body={draft.content} editor={editor} disabled={busy || Boolean(state.source.archivedAt)} sharedSource />
      <MarkdownEditor ref={editor} value={draft.content} onChange={content => setDraft(current => current ? { ...current, content } : current)} ariaLabel="Series source Markdown editor" bookId={state.source.bookId} readOnly={busy || Boolean(state.source.archivedAt)} /><div className="codex-editor-actions"><Button className="codex-icon-action" variant="ghost" leadingIcon={<Undo2 />} aria-label="Undo series source edit" onClick={() => editor.current?.undo()} /><Button className="codex-icon-action" variant="ghost" leadingIcon={<Redo2 />} aria-label="Redo series source edit" onClick={() => editor.current?.redo()} /></div>
    </div> : <p>Loading series source…</p>}{error && <p role="alert">{error}</p>}
  </IllustrationModal>
}
export function CodexScopeControls({ entry, seriesId, disabled, onBeforeChange, onRefresh }: { entry: CodexEntryEntity; seriesId?: string; disabled?: boolean; onBeforeChange: () => Promise<void>; onRefresh: () => Promise<void> }) {
  const [sourceId, setSourceId] = useState(''), [reset, setReset] = useState<{ local: CodexEntryEntity; source: CodexEntryEntity; localRelationships: unknown; sourceRelationships: unknown }>(), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  async function run(action: () => Promise<unknown>) { if (busy) return; setBusy(true); setError(''); try { await onBeforeChange(); await action(); await onRefresh() } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  return <div className="codex-scope-controls"><strong>{codexScopeLabel(entry)}</strong>{entry.seriesSourceId ? <><p>Edits for this book create an independent full entry. Shared changes require Edit series source.</p>{entry.codexScope === 'inherited' && <Button size="small" disabled={busy || disabled || Boolean(entry.archivedAt)} onClick={() => { void run(() => editCodexForBook(entry.bookId, entry.id)) }}>Edit for this book</Button>}<Button size="small" disabled={busy || disabled} onClick={() => { void run(async () => setSourceId(entry.seriesSourceId!)) }}>Edit series source</Button><Button size="small" variant="ghost" disabled={busy || disabled} onClick={() => { void run(() => setSeriesEntryHidden(entry.bookId, entry.id, true)) }}>Hide in this book</Button>{entry.codexScope === 'override' && <Button size="small" variant="danger" disabled={busy || disabled} onClick={() => { void run(async () => { const local = await getEntity<CodexEntryEntity>(entry.id); const shared = await readSeriesSource(entry.bookId, entry.seriesSourceId!); if (!local) throw new Error('The entry is missing.'); setReset({ local, source: shared.source, localRelationships: await listOutgoingCodexDependencies(entry.bookId, entry.id), sourceRelationships: shared.edges }) }) }}>Reset to series…</Button>}</> : seriesId && <Button size="small" disabled={busy || disabled} onClick={() => { void run(() => promoteCodexToSeries(entry.bookId, entry.id)) }}>Share with series</Button>}
    {reset && <IllustrationModal title="Reset this book’s override" onClose={() => setReset(undefined)} footer={<><Button variant="ghost" disabled={busy} onClick={() => setReset(undefined)}>Cancel</Button><Button variant="danger" disabled={busy} onClick={() => { void run(async () => { await resetCodexToSeries(entry.bookId, entry.id, JSON.stringify(reset.local)); setReset(undefined) }) }}>Discard override and inherit</Button></>}><p>The local title, body, type, triggers, relationships, checkpoints, and image will be replaced by the current series source.</p><div className="series-reset-comparison"><section><h3>Local changes to discard</h3><CodexIllustration entry={reset.local} readOnly><span>Local image</span></CodexIllustration><pre>{JSON.stringify({ title: reset.local.title, category: reset.local.category, triggers: reset.local.autoIncludeTriggers, image: reset.local.primaryImageId, relationships: reset.localRelationships, checkpoints: reset.local.checkpoints }, null, 2)}</pre><pre>{reset.local.content}</pre></section><section><h3>Series source</h3><CodexIllustration entry={reset.source} readOnly><span>Series image</span></CodexIllustration><pre>{JSON.stringify({ title: reset.source.title, category: reset.source.category, triggers: reset.source.autoIncludeTriggers, image: reset.source.primaryImageId, relationships: reset.sourceRelationships, checkpoints: reset.source.checkpoints }, null, 2)}</pre><pre>{reset.source.content}</pre></section></div>{error && <p role="alert">{error}</p>}</IllustrationModal>}
    {sourceId && <SeriesSourceEditor bookId={entry.bookId} sourceId={sourceId} onClose={() => { setSourceId(''); void onRefresh() }} />}{error && <p role="alert">{error}</p>}
  </div>
}
export function SeriesCodexManager({ bookId, onBeforeChange, onRefresh }: { bookId: string; onBeforeChange: () => Promise<void>; onRefresh: () => Promise<void> }) {
  const [state, setState] = useState<Awaited<ReturnType<typeof seriesCodexState>>>(), [sourceId, setSourceId] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [title, setTitle] = useState(''), [deleting, setDeleting] = useState<CodexEntryEntity>()
  const reload = async () => setState(await seriesCodexState(bookId))
  useEffect(() => { let active = true; const load = () => { void seriesCodexState(bookId).then(value => { if (active) setState(value) }).catch(reason => { if (active) setError(reason.message) }) }; load(); window.addEventListener('arc-series-codex-changed', load); return () => { active = false; window.removeEventListener('arc-series-codex-changed', load) } }, [bookId])
  async function run(action: () => Promise<unknown>) { if (busy) return; setBusy(true); setError(''); try { await onBeforeChange(); await action(); await reload(); await onRefresh() } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  if (!state?.series) return null
  return <details className="series-codex-manager"><summary>Series Codex · {state.series.title}</summary><p>Shared sources affect {state.books.length} books. Book-only entries stay private to their book.</p>{state.sources.map(source => { const local = state.locals.find(item => item.seriesSourceId === source.id); return <article key={source.id}><strong>{source.title}</strong><small>{source.archivedAt ? ' · archived across series' : local?.hiddenInBook ? ' · hidden in this book' : local ? ` · ${codexScopeLabel(local)}` : ''}</small><div><Button size="small" disabled={busy} onClick={() => { void run(async () => setSourceId(source.id)) }}>Edit series source</Button>{local && <Button size="small" variant="ghost" disabled={busy} onClick={() => { void run(() => setSeriesEntryHidden(bookId, local.id, !local.hiddenInBook)) }}>{local.hiddenInBook ? 'Unhide in this book' : 'Hide in this book'}</Button>}<Button size="small" variant="ghost" disabled={busy} onClick={() => { void run(() => archiveSeriesSource(bookId, source.id, !source.archivedAt)) }}>{source.archivedAt ? 'Restore series source' : 'Archive series source'}</Button><Button size="small" variant="danger" disabled={busy} onClick={() => setDeleting(source)}>Delete series source…</Button></div></article> })}
    <Input label="New series entry title" value={title} onChange={event => setTitle(event.target.value)} /><Button size="small" disabled={busy || !title.trim()} onClick={() => { void run(async () => { if (state.sources.some(source => source.title.trim().toLowerCase() === title.trim().toLowerCase())) throw new Error('A series entry with this title already exists.'); const local = await createCodexEntry(bookId, title.trim()); const source = await promoteCodexToSeries(bookId, local.id); setTitle(''); setSourceId(source.id) }) }}>Create series entry</Button>
    {sourceId && <SeriesSourceEditor bookId={bookId} sourceId={sourceId} onClose={() => { setSourceId(''); void run(async () => {}) }} />}
    {deleting && <IllustrationModal title={`Delete shared source: ${deleting.title}`} onClose={() => setDeleting(undefined)} footer={<><Button variant="ghost" disabled={busy} onClick={() => setDeleting(undefined)}>Cancel</Button><Button variant="danger" disabled={busy} onClick={() => { void run(async () => { await deleteSeriesSource(bookId, deleting.id); setDeleting(undefined) }) }}>Delete across series</Button></>}><p>This removes the source from {state.books.length} books. Local overrides survive as book-only entries with their own media.</p>{error && <p role="alert">{error}</p>}</IllustrationModal>}{error && <p role="alert">{error}</p>}
  </details>
}
