import { useEffect, useState } from 'react'
import type { ArcEntity } from './persistence'
import { emptyAuthorPlanning, manuscriptWords, taskStatusLabels, type AuthorGoal, type AuthorTask, type AuthorPlanning } from './author-planning'
import { readAuthorPlanning, saveAuthorPlanning } from './author-planning-service'
export default function AuthorGoalsTasks({ bookId, liveScene, onOpen }: { bookId: string; liveScene?: { id: string; content: string }; onOpen: (id: string) => void }) {
  const [planning, setPlanning] = useState<AuthorPlanning>(emptyAuthorPlanning), [entities, setEntities] = useState<ArcEntity[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false)
  const [filter, setFilter] = useState('all'), [goal, setGoal] = useState<AuthorGoal>(), [task, setTask] = useState<AuthorTask>(), [draftBase, setDraftBase] = useState<AuthorPlanning>(), [target, setTarget] = useState('')
  const accept = (value: Awaited<ReturnType<typeof readAuthorPlanning>>) => { setPlanning(value.planning); setEntities(value.entities); setLoaded(true) }
  useEffect(() => { let alive = true; const refresh = () => { void readAuthorPlanning(bookId).then(value => { if (alive) accept(value) }).catch(e => { if (alive) setError(e.message) }) }; refresh(); window.addEventListener('arc-entity-changed', refresh); window.addEventListener('focus', refresh); return () => { alive = false; window.removeEventListener('arc-entity-changed', refresh); window.removeEventListener('focus', refresh) } }, [bookId, liveScene?.id])
  const active = planning.goals.find(g => !g.completed), words = manuscriptWords(entities, liveScene)
  async function save(next: AuthorPlanning, expected = planning) { if (busy) return; setBusy(true); setError(''); try { accept(await saveAuthorPlanning(bookId, expected, next)); setGoal(undefined); setTask(undefined); setDraftBase(undefined) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  function editGoal(value: AuthorGoal) { setTask(undefined); setGoal(structuredClone(value)); setTarget(String(value.targetWords ?? '')); setDraftBase(structuredClone(planning)); setError('') }
  function editTask(value: AuthorTask) { setGoal(undefined); setTask(structuredClone(value)); setDraftBase(structuredClone(planning)); setError('') }
  function move(id: string, delta: number) { const tasks = [...planning.tasks], index = tasks.findIndex(t => t.id === id), to = index + delta; if (to < 0 || to >= tasks.length) return; [tasks[index], tasks[to]] = [tasks[to], tasks[index]]; void save({ ...planning, tasks }) }
  const links = entities.filter(e => ['scene', 'chapter', 'note', 'codexEntry'].includes(e.type) && !e.hiddenInBook)
  return <details className="author-planning" open><summary>Goals &amp; tasks</summary>
    {active ? <section className="author-active-goal"><strong>{active.title}</strong>{active.description && <p>{active.description}</p>}{active.targetWords && <><progress aria-label="Manuscript word target" value={Math.min(words, active.targetWords)} max={active.targetWords} /><p>{words.toLocaleString()} / {active.targetWords.toLocaleString()} manuscript words</p></>}<div className="author-actions"><button type="button" disabled={busy} onClick={() => editGoal(active)}>Edit goal</button><button type="button" disabled={busy} onClick={() => { void save({ ...planning, goals: planning.goals.map(g => g.id === active.id ? { ...g, completed: true } : g) }) }}>Complete goal</button></div></section> : <button type="button" disabled={busy || !loaded} onClick={() => editGoal({ id: `goal-${crypto.randomUUID()}`, title: '', description: '', completed: false })}>New goal</button>}
    <p className="author-help">{active?.targetWords ? 'Progress counts manuscript prose. Complete a goal when you decide it is finished.' : `${words.toLocaleString()} manuscript words. Goals are completed explicitly.`}</p>
    <div className="author-actions"><button type="button" disabled={busy || !loaded} onClick={() => editTask({ id: `task-${crypto.randomUUID()}`, title: '', notes: '', status: 'todo' })}>New task</button><select aria-label="Filter author tasks" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All tasks</option>{Object.entries(taskStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    <ol className="author-task-list">{planning.tasks.filter(t => filter === 'all' || t.status === filter).map(t => { const link = links.find(e => e.id === t.linkedEntityId); return <li key={t.id}><strong>{t.title}</strong>{t.notes && <p>{t.notes}</p>}{t.goalId && <small>{planning.goals.find(g => g.id === t.goalId)?.title || 'Unavailable goal'}</small>}{t.linkedEntityId && (link ? <button className="author-task-link" type="button" onClick={() => onOpen(link.id)}>{link.title} · {link.type === 'codexEntry' ? 'Codex' : link.type}</button> : <small>Unavailable linked item</small>)}<div className="author-actions"><select aria-label={`Status: ${t.title}`} disabled={busy} value={t.status} onChange={e => { void save({ ...planning, tasks: planning.tasks.map(item => item.id === t.id ? { ...item, status: e.target.value as AuthorTask['status'] } : item) }) }}>{Object.entries(taskStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" disabled={busy} onClick={() => editTask(t)}>Edit</button><button aria-label={`Move ${t.title} up`} type="button" disabled={busy || planning.tasks[0].id === t.id} onClick={() => move(t.id, -1)}>↑</button><button aria-label={`Move ${t.title} down`} type="button" disabled={busy || planning.tasks.at(-1)?.id === t.id} onClick={() => move(t.id, 1)}>↓</button><button type="button" disabled={busy} onClick={() => { if (window.confirm(`Delete task “${t.title}”?`)) void save({ ...planning, tasks: planning.tasks.filter(item => item.id !== t.id) }) }}>Delete</button></div></li> })}</ol>
    {!planning.tasks.some(t => filter === 'all' || t.status === filter) && <p>No tasks in this view.</p>}
    {(goal || task) && <form className="author-draft" onSubmit={e => { e.preventDefault(); if (!draftBase) return; if (goal) { const item = { ...goal, targetWords: target.trim() ? Number(target) : undefined }; void save({ ...draftBase, goals: draftBase.goals.some(g => g.id === goal.id) ? draftBase.goals.map(g => g.id === goal.id ? item : g) : [...draftBase.goals, item] }, draftBase) } else if (task) void save({ ...draftBase, tasks: draftBase.tasks.some(t => t.id === task.id) ? draftBase.tasks.map(t => t.id === task.id ? task : t) : [...draftBase.tasks, task] }, draftBase) }}><fieldset disabled={busy}><legend>{goal ? 'Goal' : 'Task'} details</legend><label>Title<input aria-label={goal ? 'Goal title' : 'Task title'} required maxLength={160} value={goal?.title ?? task?.title ?? ''} onChange={e => goal ? setGoal({ ...goal, title: e.target.value }) : setTask({ ...task!, title: e.target.value })} /></label><label>{goal ? 'Description' : 'Notes'}<textarea value={goal?.description ?? task?.notes ?? ''} onChange={e => goal ? setGoal({ ...goal, description: e.target.value }) : setTask({ ...task!, notes: e.target.value })} /></label>{goal && <label>Target manuscript words (optional)<input aria-label="Target manuscript words" type="number" min="1" step="1" value={target} onChange={e => setTarget(e.target.value)} /></label>}{task && <><label>Goal<select aria-label="Task goal" value={task.goalId ?? ''} onChange={e => setTask({ ...task, goalId: e.target.value || undefined })}><option value="">No goal</option>{planning.goals.filter(g => !g.completed || task.goalId === g.id).map(g => <option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>Linked item<select aria-label="Task linked item" value={task.linkedEntityId ?? ''} onChange={e => setTask({ ...task, linkedEntityId: e.target.value || undefined })}><option value="">No link</option>{task.linkedEntityId && !links.some(e => e.id === task.linkedEntityId) && <option value={task.linkedEntityId}>Unavailable linked item</option>}{links.map(e => <option key={e.id} value={e.id}>{e.title} · {e.type}</option>)}</select></label></>}<div className="author-actions"><button type="button" onClick={() => { setGoal(undefined); setTask(undefined) }}>Cancel</button><button type="submit">Save {goal ? 'goal' : 'task'}</button></div></fieldset></form>}
    {planning.goals.some(g => g.completed) && <details><summary>Completed goals · {planning.goals.filter(g => g.completed).length}</summary>{planning.goals.filter(g => g.completed).map(g => <p key={g.id}><strong>{g.title}</strong>{g.description && ` — ${g.description}`}</p>)}</details>}
    {error && <p role="alert">{error}</p>}
  </details>
}
