import { useEffect, useRef, useState } from 'react'
import { createCharacterChat, listCharacterCandidates, moveCharacterChat, type CharacterParticipant } from './character-chat'
import { readTimelineWorld } from './codex-timeline-service'
import { timelineScenes, type TimelineWorld } from './codex-timeline'
import type { CodexEntryEntity } from './persistence'
import { updateEntityAtomically } from './persistence'
import { updateChat, type ChatEntity } from './chat-service'
import { listGalleryImages } from './image-store'
import type { GalleryImage } from './image-generation-types'
import IllustrationModal from './IllustrationModal'

export function CharacterChatSetup({ bookId, initialEntryId, currentSceneId, caret, chat, onClose, onOpen }: { bookId: string; initialEntryId?: string; currentSceneId?: string; caret?: number; chat?: ChatEntity; onClose: () => void; onOpen: (id: string) => void }) {
  const [entries, setEntries] = useState<CodexEntryEntity[]>([]), [world, setWorld] = useState<TimelineWorld>(), [participants, setParticipants] = useState<Array<Pick<CharacterParticipant, 'entryId' | 'label'>>>(chat?.character?.participants ?? []), [sceneId, setSceneId] = useState(chat?.character?.cutoff.sceneId ?? currentSceneId ?? ''), [position, setPosition] = useState<'start' | 'end' | 'caret' | 'saved'>(chat ? 'saved' : caret !== undefined ? 'caret' : 'end'), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { let live = true; void Promise.all([listCharacterCandidates(bookId), readTimelineWorld(bookId)]).then(([entries, world]) => { if (!live) return; setEntries(entries); setWorld(world); if (!chat && initialEntryId) { const entry = entries.find(e => e.id === initialEntryId); if (entry) setParticipants([{ entryId: entry.id, label: entry.title }]) } }).catch(e => { if (live) setError(e.message) }); return () => { live = false } }, [bookId, initialEntryId, chat?.id])
  const scene = world && timelineScenes(world, bookId).find(scene => scene.id === sceneId)
  const start = async (restart = false) => { if (busy || !scene) return; setBusy(true); setError(''); try { const cutoff = { bookId, sceneId, position: position === 'start' ? 0 : position === 'caret' ? caret! : position === 'saved' ? chat!.character!.cutoff.position! : String(scene.content ?? '').length }; const next = chat ? await moveCharacterChat(chat.id, cutoff, restart) : await createCharacterChat(bookId, participants, cutoff); onOpen(next.id); onClose() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <IllustrationModal title={chat ? 'Character story position' : 'New character chat'} onClose={() => { if (!busy) onClose() }} footer={<><button type="button" disabled={busy} onClick={onClose}>Cancel</button>{chat && <button type="button" disabled={busy || !scene} onClick={() => { void start(true) }}>Restart here without history</button>}<button type="button" disabled={busy || !scene || !participants.length} onClick={() => { void start() }}>{chat ? 'Use this position' : 'Start character chat'}</button></>}>
    <div className="character-chat-setup"><p>Each participant’s full Codex profile is included automatically, together with manuscript up to the selected story position. In Chat context settings, you can add Codex entries, notes, manuscript sections and summaries as references for this conversation.</p>
    {!chat && <fieldset disabled={busy}><legend>Participants</legend>{entries.map(entry => { const selected = participants.find(item => item.entryId === entry.id); return <div key={entry.id}><label><input type="checkbox" checked={Boolean(selected)} onChange={e => setParticipants(value => e.target.checked ? [...value, { entryId: entry.id, label: entry.title }] : value.filter(p => p.entryId !== entry.id))} />{entry.title} · {entry.category}</label>{selected && <label>Display label<input value={selected.label} onChange={e => setParticipants(value => value.map(p => p.entryId === entry.id ? { ...p, label: e.target.value } : p))} /></label>}</div> })}{!entries.length && <p>Create a Character entry or mark another Codex entry as a roleplay participant.</p>}</fieldset>}
    <label>Current scene<select aria-label="Character chat scene" value={sceneId} disabled={busy} onChange={e => { setSceneId(e.target.value); setPosition('end') }}><option value="">Choose a scene</option>{world && timelineScenes(world, bookId).map(scene => <option key={scene.id} value={scene.id}>{scene.title}</option>)}</select></label><label>Cutoff<select aria-label="Character chat cutoff" value={position} disabled={busy} onChange={e => setPosition(e.target.value as typeof position)}><option value="start">Start of scene</option><option value="end">End of scene</option>{caret !== undefined && currentSceneId === sceneId && <option value="caret">Captured editor caret</option>}{chat && sceneId === chat.character?.cutoff.sceneId && <option value="saved">Saved position</option>}</select></label>
    {chat && <p>Moving earlier creates a new chat with empty history. Moving forward changes subsequent requests. Restart also starts fresh at the chosen position.</p>}{error && <p role="alert">{error}</p>}</div>
  </IllustrationModal>
}
export function CharacterPosition({ chat, disabled, onOpen }: { chat: ChatEntity; disabled: boolean; onOpen: (id: string) => void }) {
  const [open, setOpen] = useState(false)
  return chat.character ? <div className="character-position"><p>Character chat · {chat.character.participants.map(p => p.label).join(', ')}</p><button type="button" disabled={disabled} onClick={() => setOpen(true)}>Story position / restart</button>{open && <CharacterChatSetup bookId={chat.bookId} chat={chat} onClose={() => setOpen(false)} onOpen={onOpen} />}</div> : null
}
export function RoleplayParticipant({ entry, disabled, onBeforeChange, onRefresh, onStart }: { entry: CodexEntryEntity; disabled?: boolean; onBeforeChange: () => Promise<void>; onRefresh: () => Promise<void>; onStart: () => void }) {
  const [error, setError] = useState('')
  const eligible = entry.typeId === 'lore-character' || entry.roleplayParticipant === true
  return <div className="roleplay-participant">{entry.typeId !== 'lore-character' && <label><input type="checkbox" disabled={disabled || entry.codexScope === 'inherited'} checked={entry.roleplayParticipant === true} onChange={e => { const enabled = e.target.checked; void onBeforeChange().then(() => updateEntityAtomically<CodexEntryEntity>(entry.id, current => { if (current.type !== 'codexEntry' || current.bookId !== entry.bookId || current.codexScope === 'inherited') throw new Error('Edit for this book first.'); return { ...current, roleplayParticipant: enabled, updatedAt: Date.now() } })).then(onRefresh).catch(e => setError(e.message)) }} />Use as roleplay participant</label>}{eligible && <button type="button" disabled={disabled} onClick={onStart}>Chat with character</button>}{error && <p role="alert">{error}</p>}</div>
}
export function ChatImageReferences({ chat, disabled, onChange }: { chat: ChatEntity; disabled?: boolean; onChange: (chat: ChatEntity) => void }) {
  const busy = useRef(false)
  async function save(ids: string[]) { if (busy.current || disabled) return; busy.current = true; try { onChange(await updateChat(chat.id, { directImageReferenceIds: [...new Set(ids)] })) } catch (error) { setError((error as Error).message) } finally { busy.current = false } }
  const [assets, setAssets] = useState<GalleryImage[]>([]), [error, setError] = useState('')
  useEffect(() => { let current = true; void listGalleryImages(chat.bookId).then(assets => { if (current) setAssets(assets.filter(a => a.kind !== 'video')) }).catch(e => { if (current) setError(e.message) }); return () => { current = false } }, [chat.bookId])
  return <details className="chat-image-references"><summary>Image references · {chat.directImageReferenceIds?.length ?? 0}</summary><p>Used only when you explicitly request an image. No reference image is selected automatically.</p>{assets.map(asset => <label key={asset.id}><input type="checkbox" disabled={disabled} checked={chat.directImageReferenceIds?.includes(asset.id) ?? false} onChange={e => { const ids = chat.directImageReferenceIds ?? [], next = e.target.checked ? [...ids, asset.id] : ids.filter(id => id !== asset.id); void save(next) }} />{asset.prompt || 'Saved image'}</label>)}{(chat.directImageReferenceIds ?? []).filter(id => !assets.some(asset => asset.id === id)).map(id => <button type="button" disabled={disabled} key={id} onClick={() => { void save((chat.directImageReferenceIds ?? []).filter(value => value !== id)) }}>Remove unavailable reference</button>)}{!assets.length && <p>No saved still images in this book.</p>}{error && <p role="alert">{error}</p>}</details>
}
