import { useEffect, useRef, useState } from 'react'
import type { CodexEntryEntity } from './persistence'
import { getEntity } from './persistence'
import { checkpointPlaced, resolveCodexState, timelineScenes, type CodexCheckpoint, type TimelineWorld, type TimelineMode } from './codex-timeline'
import { generateTimelineSummary, readTimelineWorld, saveCodexCheckpoints } from './codex-timeline-service'

export default function CodexTimeline({ bookId, entry, currentSceneId, disabled, onBeforeChange, onRefresh, onViewChange }: { bookId: string; entry: CodexEntryEntity; currentSceneId?: string; disabled?: boolean; onBeforeChange: () => Promise<void>; onRefresh: () => Promise<void>; onViewChange?: (nonBaseline: boolean) => void }) {
  const [world, setWorld] = useState<TimelineWorld>(), [value, setValue] = useState(entry), [view, setView] = useState('baseline'), [draft, setDraft] = useState<CodexCheckpoint>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [summaryMode, setSummaryMode] = useState<TimelineMode>('cutoff')
  const controller = useRef<AbortController | null>(null)
  const refresh = async () => { const latest = await getEntity<CodexEntryEntity>(entry.id); if (latest) setValue(latest); setWorld(await readTimelineWorld(bookId)) }
  useEffect(() => { let live = true; const load = () => { void Promise.all([getEntity<CodexEntryEntity>(entry.id), readTimelineWorld(bookId)]).then(([entry, world]) => { if (live) { if (entry) setValue(entry); setWorld(world) } }).catch(e => { if (live) setError(e.message) }) }; load(); window.addEventListener('focus', load); window.addEventListener('arc-series-codex-changed', load); return () => { live = false; controller.current?.abort(); window.removeEventListener('focus', load); window.removeEventListener('arc-series-codex-changed', load) } }, [bookId, entry.id])
  const readOnly = disabled || entry.codexScope === 'inherited' || Boolean(entry.archivedAt)
  const points = value.checkpoints ?? []
  let resolved: ReturnType<typeof resolveCodexState> | undefined, resolutionError = ''
  try { if (world && currentSceneId) resolved = resolveCodexState(value, { bookId, sceneId: currentSceneId }, world) } catch (reason) { resolutionError = (reason as Error).message }
  const run = async (action: () => Promise<void>) => { if (busy) return; setBusy(true); setError(''); try { await onBeforeChange(); await action(); await refresh(); await onRefresh() } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  const choose = (next: string) => { void run(async () => { setView(next); setDraft(undefined); onViewChange?.(next !== 'baseline') }) }
  const selected = points.find(point => point.id === view)
  return <details className="codex-timeline"><summary>Story checkpoints · {points.length}{resolved ? ` · ${resolved.checkpointId === 'baseline' ? 'Baseline active' : 'Checkpoint active'}` : ''}</summary>
    <p>Baseline contains facts valid at the start. Checkpoints take effect at the start of their scene. Inspecting or editing one does not move the AI’s story cutoff.</p>
    <label>View<select aria-label="Codex timeline view" disabled={busy || Boolean(draft)} value={view} onChange={e => choose(e.target.value)}><option value="baseline">Baseline</option><option value="as-of">As of current scene</option>{points.map(point => <option key={point.id} value={point.id}>{point.label}{world && !checkpointPlaced(point, world) ? ' · Unplaced' : ''}{point.id === resolved?.checkpointId ? ' · Active' : ''}</option>)}</select></label>
    <ul>{points.map(point => <li key={point.id} className={world && !checkpointPlaced(point, world) ? 'unplaced' : ''}><strong>{point.label}</strong> · {world?.books.find(book => book.id === point.anchorBookId)?.title || 'Unavailable book'} / {world?.outline.find(scene => scene.id === point.sceneId)?.title || 'Unplaced scene'}{point.id === resolved?.checkpointId ? ' · Active' : ''}</li>)}</ul>
    {view === 'baseline' && <p>Use the baseline editor below.</p>}
    {view === 'as-of' && <><p>{resolutionError || (!resolved ? 'Choose a current scene to resolve this entry.' : resolved.checkpointId === 'baseline' ? 'Baseline at the current scene' : 'Eligible checkpoint body')}</p>{resolved && <pre>{resolved.content}</pre>}</>}
    {selected && !draft && <><pre>{selected.content || 'Empty state'}</pre><button type="button" disabled={readOnly || busy} onClick={() => setDraft({ ...selected })}>Edit checkpoint</button><button type="button" disabled={readOnly || busy} onClick={() => { void run(async () => { await saveCodexCheckpoints(bookId, entry.id, points, points.filter(point => point.id !== selected.id)); setView('baseline'); onViewChange?.(false) }) }}>Delete checkpoint</button></>}
    {!draft && <button type="button" disabled={readOnly || busy} onClick={() => { void run(async () => { const latest = await getEntity<CodexEntryEntity>(entry.id); setDraft({ id: `checkpoint-${crypto.randomUUID()}`, label: '', anchorBookId: bookId, sceneId: currentSceneId ?? '', content: resolved?.content ?? latest?.content ?? '', revision: Date.now() }); onViewChange?.(true) }) }}>New checkpoint</button>}
    {draft && <fieldset disabled={busy || readOnly}><label>Checkpoint label<input aria-label="Checkpoint label" value={draft.label} onChange={e => setDraft({ ...draft, label: e.target.value })} /></label><label>Book<select aria-label="Checkpoint book" value={draft.anchorBookId} onChange={e => setDraft({ ...draft, anchorBookId: e.target.value, sceneId: '' })}>{world?.books.filter(book => book.id === bookId || value.seriesSourceId || value.codexScope === 'series').map(book => <option key={book.id} value={book.id}>{book.title} · {book.seriesOrder || 'order unset'}</option>)}</select></label><label>Effective from scene<select aria-label="Checkpoint scene" value={draft.sceneId} onChange={e => setDraft({ ...draft, sceneId: e.target.value })}><option value="">Choose scene</option>{world && timelineScenes(world, draft.anchorBookId).map(scene => <option key={scene.id} value={scene.id}>{scene.title}</option>)}{draft.sceneId && world && !checkpointPlaced(draft, world) && <option value={draft.sceneId}>Unplaced — choose a new anchor</option>}</select></label><label>Full state body<textarea aria-label="Checkpoint body" rows={10} value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} /></label><p>Unsaved checkpoint changes. This is a full snapshot, independent of the baseline.</p><button type="button" onClick={() => { setDraft(undefined); onViewChange?.(view !== 'baseline') }}>Cancel checkpoint edit</button><button type="button" disabled={!draft.label.trim() || !draft.sceneId} onClick={() => { void run(async () => { await saveCodexCheckpoints(bookId, entry.id, points, [...points.filter(point => point.id !== draft.id), draft]); setView(draft.id); setDraft(undefined); onViewChange?.(true) }) }}>Save checkpoint</button></fieldset>}
    {!draft && view !== 'as-of' && <div><label>Summary mode<select value={summaryMode} onChange={e => setSummaryMode(e.target.value as TimelineMode)}><option value="cutoff">Story cutoff</option><option value="strict">Character cutoff (body only)</option></select></label><button type="button" disabled={busy || disabled} onClick={() => { void run(async () => { controller.current = new AbortController(); await generateTimelineSummary(bookId, entry.id, selected?.id ?? 'baseline', summaryMode, controller.current.signal) }) }}>Summarize this state</button>{busy && controller.current && <button type="button" onClick={() => controller.current?.abort()}>Stop summary</button>}<small>Uses the Support model. Cached for this exact body, story order, and cutoff mode.</small></div>}
    {(error || resolutionError) && <p role="alert">{error || resolutionError}</p>}
  </details>
}
