import { useState } from 'react'
import type { AiSettings } from './ai-settings'
import type { ImageModel, ImageProvider, ImageSettings } from './image-generation-types'
import { documentedImageModels, imageSize, imageFavorite, imageProviderNames, imageRatio, IMAGE_PROVIDERS, loadImageSettings, resolveImageKey, saveImageSettings } from './image-settings'
import { fetchImageModels } from './image-providers'
export default function ImageSettingsPanel({ ai }: { ai: AiSettings }) {
  const [settings, setSettings] = useState<ImageSettings>(loadImageSettings)
  const [provider, setProvider] = useState<ImageProvider>('nanogpt'), [query, setQuery] = useState('')
  const [catalogs, setCatalogs] = useState<Partial<Record<ImageProvider, ImageModel[]>>>(() => { try { const data = JSON.parse(localStorage.getItem('arc-image-catalog-v1') || '{}'); return Object.fromEntries(IMAGE_PROVIDERS.filter((p) => Array.isArray(data?.[p])).map((p) => [p, data[p].filter((m: ImageModel) => m?.provider === p && typeof m.id === 'string' && typeof m.name === 'string' && Array.isArray(m.sizes) && m.sizes.length && m.sizes.every((s) => typeof s?.value === 'string' && imageSize(s.value)))])) } catch { return {} } })
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState(''), [dirty, setDirty] = useState(false)
  const change = (value: ImageSettings) => { setSettings(value); setDirty(true); setMessage('') }
  const models = catalogs[provider] ?? documentedImageModels.filter((m) => m.provider === provider)
  const refresh = async () => {
    setBusy(true); setError('')
    const selectedProvider = provider
    try {
      const models = await fetchImageModels(selectedProvider, resolveImageKey(selectedProvider, settings, ai))
      const next = { ...catalogs, [selectedProvider]: models }
      setCatalogs(next)
      try { localStorage.setItem('arc-image-catalog-v1', JSON.stringify(next)) } catch { /* Favorites can still be saved separately. */ }
      setMessage(selectedProvider === 'pruna' ? 'P-Image presets use Pruna’s documented dimensions.' : `${models.length} text-to-image models with supported sizes loaded.`)
    } catch (e) { setError(e instanceof Error ? e.message : 'Models could not be loaded.') }
    finally { setBusy(false) }
  }
  const save = () => { try { setSettings(saveImageSettings(settings)); setDirty(false); setMessage('Image settings saved'); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Settings could not be saved.') } }
  return <section className="image-settings"><p className="image-help">Image providers and favorites apply to all books on this device. Save changes before generating.</p><h2>Providers</h2>{IMAGE_PROVIDERS.map((p) => <label key={p}>{imageProviderNames[p]} API key<input type="password" autoComplete="off" value={settings.keys[p]} placeholder={p === 'pruna' ? 'Enter Pruna API key' : 'Use this provider’s AI-settings key'} onChange={(e) => change({ ...settings, keys: { ...settings.keys, [p]: e.target.value } })} /><small>{settings.keys[p] ? 'Using the image key' : p !== 'pruna' && resolveImageKey(p, settings, ai) ? 'Using saved AI-settings key' : 'No key configured'}</small></label>)}<h2>Favorite models</h2><label>Provider<select value={provider} onChange={(e) => { setProvider(e.target.value as ImageProvider); setQuery('') }}>{IMAGE_PROVIDERS.map((p) => <option key={p} value={p}>{imageProviderNames[p]}</option>)}</select></label><button type="button" disabled={busy} onClick={() => { void refresh() }}>{busy ? 'Loading models…' : provider === 'pruna' ? 'Load documented models' : 'Refresh models'}</button><label>Find a model<input type="search" placeholder="Search models" value={query} onChange={(e) => setQuery(e.target.value)} /></label><div className="image-catalog">{models.filter((m) => `${m.id} ${m.name}`.toLowerCase().includes(query.toLowerCase())).slice(0, 100).map((m) => <div key={m.id}><span>{m.name}<small>{m.id}</small></span><button type="button" disabled={settings.favorites.some((f) => f.provider === m.provider && f.id === m.id)} onClick={() => change({ ...settings, favorites: [...settings.favorites, imageFavorite(m, settings.favorites)] })}>Favorite</button></div>)}{!models.length && <p>Refresh models to discover supported image sizes.</p>}</div>{settings.favorites.map((f, index) => {
    const update = (patch: Partial<typeof f>) => change({ ...settings, favorites: settings.favorites.map((m, i) => i === index ? { ...m, ...patch } : m) })
    const discovered = catalogs[f.provider]?.find((m) => m.id === f.id)
    return <article className="image-favorite" key={`${f.provider}/${f.id}`}><h3>{imageProviderNames[f.provider]} · {f.name}</h3><label>Chat model alias<input maxLength={64} value={f.alias} onChange={(e) => { const alias = e.target.value; change({ ...settings, defaultAlias: settings.defaultAlias === f.alias ? alias : settings.defaultAlias, favorites: settings.favorites.map((m, i) => i === index ? { ...m, alias } : m) }) }} /></label><fieldset><legend>Enabled ratios and sizes</legend>{f.sizes.map((s) => <label className="image-check" key={s.value}><input type="checkbox" checked={f.enabledSizes.includes(s.value)} onChange={(e) => { const enabledSizes = e.target.checked ? [...f.enabledSizes, s.value] : f.enabledSizes.filter((v) => v !== s.value); update({ enabledSizes, defaultSize: enabledSizes.includes(f.defaultSize) ? f.defaultSize : enabledSizes[0] || '' }) }} />{imageRatio(s)} · {s.width} × {s.height}</label>)}</fieldset><label>Default size<select value={f.defaultSize} onChange={(e) => update({ defaultSize: e.target.value })}>{f.sizes.filter((s) => f.enabledSizes.includes(s.value)).map((s) => <option key={s.value} value={s.value}>{s.value}</option>)}</select></label><label className="image-check"><input type="radio" name="default-image-model" checked={settings.defaultAlias === f.alias || (!settings.defaultAlias && index === 0)} onChange={() => change({ ...settings, defaultAlias: f.alias })} />Default image model</label>{discovered && <button type="button" onClick={() => { const enabledSizes = discovered.sizes.map((s) => s.value).filter((s) => f.enabledSizes.includes(s)); const active = enabledSizes.length ? enabledSizes : [discovered.sizes[0].value]; update({ sizes: discovered.sizes, enabledSizes: active, defaultSize: active.includes(f.defaultSize) ? f.defaultSize : active[0] }) }}>Update supported sizes</button>}<button type="button" onClick={() => change({ ...settings, favorites: settings.favorites.filter((_, i) => i !== index) })}>Remove favorite</button><a href={f.source} target="_blank" rel="noreferrer">Provider documentation</a></article>
  })}<div className="image-settings-save"><button type="button" onClick={save}>Save image settings{dirty ? ' *' : ''}</button><span role="status">{message}</span></div>{error && <p role="alert">{error}</p>}</section>
}
